[mypy]
python_version = 3.11
files = src, tests
warn_unused_configs = true
show_error_codes = true
ignore_missing_imports = true
allow_untyped_defs = true
allow_incomplete_defs = true
check_untyped_defs = false
disable_error_code = import-untyped
